# Numerical Python(Numpy) - Part 1

In [2]:
# de facto standard(사실상의 표준)
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = [1, 2, 3]
a * 3, b * 3

(array([3, 6, 9]), [1, 2, 3, 1, 2, 3, 1, 2, 3])

## 1. Numpy Dimensional array

In [8]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [10]:
type(a)

numpy.ndarray

In [12]:
a.dtype, a.shape # shape는 1, 4, 5, 8 네개 이므로 (4,)

(dtype('float64'), (4,))

## 2. Array shape

In [3]:
# Vector(1차원)
vector = np.array([1, 4, 5, 8, 9])
vector.shape

(5,)

In [17]:
# Matrix(2차원)
matrix  = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape) # 행이 2개 열이 3개
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [20]:
# Tensor(3차원 이상)
tensor = np.arange(1, 25).reshape(2, 3, 4) # reshape의 2는 큰 두개의 묶음, 3은 행 4은 열
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [27]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [29]:
# element의 개수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [32]:
# data type
# float32: 32bit로 표시 - single precision

a = np.array([1, 2, 3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [36]:
b = np.array([1, 2, 3], dtype=np.int16) # int16 안하면 기본적으로 int32이다
b

array([1, 2, 3], dtype=int16)

### reshape(원소는 그대로 놓고 행과 열을 바꿈)

In [38]:
matrix.shape

(2, 3)

In [40]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [42]:
matrix.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [52]:
matrix.reshape(3, -1), matrix.reshape(-1, 1)

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [47]:
matrix.reshape(3, -1).shape

(3, 2)

In [51]:
tensor.reshape(4, -1).shape

(4, 6)

### flatten

In [62]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [54]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

In [59]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
matrix[0][1]

2

In [65]:
# Numpy는 이렇게 가능하다
matrix[0, 1]

2

In [67]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [68]:
tensor[1, 1, 2]

19

### slicing

In [71]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
# 5, 6, 9, 10
b[1:3, 1:3] # b[행, 열] 행이 1:3(0,1,2), 열이 1:3(0,1,2)이다

array([[ 5,  6],
       [ 9, 10]])

In [75]:
# 5, 6, 7, 9, 10, 11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [79]:
# 1, 3, 9, 11
b[0::2, 1::2], b[::2, 1::2]

(array([[ 1,  3],
        [ 9, 11]]),
 array([[ 1,  3],
        [ 9, 11]]))

In [80]:
# X는 앞에 3열, y는 마지막 열
# [X,X,X,y]
# [X,X,X,y]
X, y = b[:, :-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))