###1

In [2]:
import numpy as np

In [ ]:
np.arange(1, 9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2

In [ ]:
m = np.arange(15).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
m[1, 2], m[2, 4]

(7, 14)

In [ ]:
m[1, 1:3], m[1:, 2], m[:2, 3:]

(array([6, 7]), array([ 7, 12]), array([[3, 4],
        [8, 9]]))

### 3

In [ ]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [ ]:
f[f%4==1]

array([ 1,  5,  9, 13])

In [ ]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### 4

In [ ]:
np.eye(5, 5)*2 + np.eye(5, 5, -1)*3 + np.eye(5, 5, 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5

In [ ]:
np.random.seed(seed=2021)

In [ ]:
m = np.random.uniform(0, 10, 30).reshape(5, 6).round(4) # round는 소수점 없애기
m

array([[0.6384, 4.1444, 3.3224, 7.2132, 4.7385, 7.9864],
       [0.9087, 8.7456, 7.7698, 7.7157, 0.631 , 5.9444],
       [7.9249, 2.7413, 3.7102, 8.5311, 6.7873, 7.5438],
       [4.1726, 3.209 , 3.723 , 2.7535, 6.7956, 5.8163],
       [9.702 , 4.1551, 3.3049, 9.6671, 8.259 , 3.054 ]])

In [ ]:
np.max(m)

9.702

In [ ]:
np.sum(m, axis=1)

array([28.0433, 31.7152, 37.2386, 26.47  , 38.1421])

In [ ]:
# 5-3번
np.max(m, axis=1)

array([7.9864, 8.7456, 8.5311, 6.7956, 9.702 ])

In [ ]:
# 5-4
np.mean(m, axis=0)

array([4.66932, 4.59908, 4.36606, 7.17612, 5.44228, 6.06898])

In [ ]:
# 5-5번
np.min(m, axis=0)

array([0.6384, 2.7413, 3.3049, 2.7535, 0.631 , 3.054 ])

### 6. Sorting

In [ ]:
score = np.array([[1, 2, 3, 4],[46, 99, 100, 71],[81,59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
np.sort(score)        # 이렇게하면 뒤섞인다

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [ ]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [ ]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [ ]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7

In [ ]:
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [ ]:
np.mean(dice)

3.7

### 8. 정규분포, 주식

In [8]:
# 10개만 먼저 테스트
np.random.seed(2021)
price = 10000
rate = np.random.normal(0,0.01,10)
for i in range(10):
  price = price + np.round(price*rate[i])
  print(price, end=', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [ ]:
# 250개
np.random.seed(2021)
price_list = []
rate = np.random.normal(0, 0.01, 250)
price = 10000
for i in range(250):
  price += np.round(price*rate[i])
  price_list.append(int(price))
price_list