### 5

In [1]:
import numpy as np

In [22]:
np.random.seed(2021)

In [29]:
a = np.random.uniform(0, 10, 30).reshape(5, 6).round(0)
a

array([[ 8.,  6.,  7.,  9.,  5.,  5.],
       [ 6.,  3.,  6.,  5.,  1., 10.],
       [ 5.,  1.,  8.,  2.,  2.,  7.],
       [ 7.,  1.,  4.,  8.,  8.,  8.],
       [ 9.,  3.,  2.,  7.,  7.,  1.]])

### 5-1

In [30]:
a.max(), np.max(a)

(10.0, 10.0)

### 5-2

In [31]:
np.sum(a, axis=0)

array([35., 14., 27., 31., 23., 31.])

### 5-3

In [35]:
np.argmax(a, axis=1) , list(np.argmax(a, axis=1))

(array([3, 5, 2, 3, 0], dtype=int64), [3, 5, 2, 3, 0])

In [39]:
for num, i in enumerate(list(np.argmax(a, axis=1))):
    print(a[num][i])

9.0
10.0
8.0
8.0
9.0


In [64]:
np.max(a, axis=1)

array([ 9., 10.,  8.,  8.,  9.])

### 5-4

In [40]:
np.mean(a, axis=0)

array([7. , 2.8, 5.4, 6.2, 4.6, 6.2])

### 5-5

In [41]:
np.argmin(a, axis=0)

array([2, 2, 4, 2, 1, 4], dtype=int64)

In [52]:
b = a.T
b

array([[ 8.,  6.,  5.,  7.,  9.],
       [ 6.,  3.,  1.,  1.,  3.],
       [ 7.,  6.,  8.,  4.,  2.],
       [ 9.,  5.,  2.,  8.,  7.],
       [ 5.,  1.,  2.,  8.,  7.],
       [ 5., 10.,  7.,  8.,  1.]])

In [54]:
for num, i in enumerate(list(np.argmin(a, axis=0))):
    print(b[num][i])

5.0
1.0
2.0
2.0
1.0
1.0


In [65]:
np.min(a, axis=0)

array([5., 1., 2., 2., 1., 1.])

6
- 영어성적을 기준으로 열을 재정렬

In [66]:
score = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [76]:
s = np.argsort(score[1])
s, s[::-1]

(array([0, 3, 1, 2], dtype=int64), array([2, 1, 3, 0], dtype=int64))

In [77]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [78]:
# 한줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7

In [63]:
np.mean(np.random.randint(1, 7, 100))

3.53

In [62]:
np.sum(np.random.randint(1, 7, 100)) // 100

3

### 8